"""Pre-seeded mock procurement data. Resets on server restart."""

from datetime import date

from api.models import (
    CatalogItem,
    Contract,
    ContractStatus,
    Invoice,
    InvoiceStatus,
    LineItem,
    POStatus,
    PurchaseOrder,
    Supplier,
    SupplierCategory,
    SupplierStatus,
)

SUPPLIERS: list[Supplier] = [
    Supplier(
        id=1,
        name="Acme Technology Solutions",
        contact_email="sales@acmetech.com",
        category=SupplierCategory.IT,
        rating=4.5,
        location="San Francisco, CA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2022, 3, 15),
        payment_terms_days=30,
    ),
    Supplier(
        id=2,
        name="SteelWorks Manufacturing",
        contact_email="procurement@steelworks.com",
        category=SupplierCategory.RAW_MATERIALS,
        rating=4.2,
        location="Pittsburgh, PA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2020, 11, 20),
        payment_terms_days=60,
    ),
    Supplier(
        id=3,
        name="CleanSpace Facilities",
        contact_email="service@cleanspace.com",
        category=SupplierCategory.FACILITIES,
        rating=3.5,
        location="Denver, CO",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2023, 4, 15),
        payment_terms_days=30,
    ),
]

PURCHASE_ORDERS: list[PurchaseOrder] = [
    # --- Acme Technology Solutions (supplier 1) ---
    PurchaseOrder(
        id=1001,
        supplier_id=1,
        line_items=[
            LineItem(description="Dell Latitude 5540 Laptop", quantity=25, unit_price=1200.00),
            LineItem(description="27-inch 4K Monitor", quantity=25, unit_price=450.00),
        ],
        total_amount=41250.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 15),
        delivery_date=date(2025, 2, 1),
    ),
    PurchaseOrder(
        id=1002,
        supplier_id=1,
        line_items=[
            LineItem(description="Cisco Meraki MR46 Access Point", quantity=40, unit_price=680.00),
        ],
        total_amount=27200.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 1),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1003,
        supplier_id=1,
        line_items=[
            LineItem(description="Security Camera - Outdoor", quantity=20, unit_price=350.00),
            LineItem(description="Network Video Recorder (NVR)", quantity=2, unit_price=2800.00),
        ],
        total_amount=12600.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2024, 11, 15),
        delivery_date=date(2024, 12, 1),
    ),
    PurchaseOrder(
        id=1004,
        supplier_id=1,
        line_items=[
            LineItem(description="Logitech MX Master 3S Mouse", quantity=50, unit_price=99.00),
            LineItem(description="Logitech K860 Keyboard", quantity=50, unit_price=69.00),
        ],
        total_amount=8400.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 20),
        delivery_date=date(2025, 3, 15),
    ),
    PurchaseOrder(
        id=1005,
        supplier_id=1,
        line_items=[
            LineItem(description="Server Rack 42U", quantity=2, unit_price=12500.00),
            LineItem(description="Rack Mount Shelf", quantity=10, unit_price=1000.00),
        ],
        total_amount=35000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 1),
        delivery_date=date(2025, 4, 1),
    ),
    PurchaseOrder(
        id=1006,
        supplier_id=1,
        line_items=[
            LineItem(description="Managed Network Switch 24-port", quantity=10, unit_price=1850.00),
        ],
        total_amount=18500.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 10),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1007,
        supplier_id=1,
        line_items=[
            LineItem(description="Dell Latitude 7450 Laptop", quantity=40, unit_price=1300.00),
        ],
        total_amount=52000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 15),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1008,
        supplier_id=1,
        line_items=[
            LineItem(description="UPS Battery Backup 1500VA", quantity=20, unit_price=480.00),
        ],
        total_amount=9600.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 5),
        delivery_date=date(2025, 1, 20),
    ),
    # --- SteelWorks Manufacturing (supplier 2) ---
    PurchaseOrder(
        id=1009,
        supplier_id=2,
        line_items=[
            LineItem(description="Steel Sheet 4x8 (Gauge 16)", quantity=500, unit_price=85.00),
        ],
        total_amount=42500.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 20),
        delivery_date=date(2025, 3, 15),
    ),
    PurchaseOrder(
        id=1010,
        supplier_id=2,
        line_items=[
            LineItem(description="Steel Rod 1-inch Diameter", quantity=1000, unit_price=12.50),
        ],
        total_amount=12500.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 10),
        delivery_date=date(2025, 2, 15),
    ),
    PurchaseOrder(
        id=1011,
        supplier_id=2,
        line_items=[
            LineItem(description="Aluminum Extrusion Profile", quantity=200, unit_price=45.00),
        ],
        total_amount=9000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 10),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1012,
        supplier_id=2,
        line_items=[
            LineItem(description="Copper Wire Spool (500m)", quantity=20, unit_price=320.00),
        ],
        total_amount=6400.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 25),
        delivery_date=date(2025, 2, 28),
    ),
    PurchaseOrder(
        id=1013,
        supplier_id=2,
        line_items=[
            LineItem(description="Stainless Steel Plate 4x4", quantity=100, unit_price=195.00),
        ],
        total_amount=19500.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 10),
        delivery_date=date(2025, 3, 20),
    ),
    PurchaseOrder(
        id=1014,
        supplier_id=2,
        line_items=[
            LineItem(description="Steel Sheet 4x8 (Gauge 16)", quantity=500, unit_price=85.00),
        ],
        total_amount=42500.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 15),
        delivery_date=date(2025, 5, 1),
    ),
    PurchaseOrder(
        id=1015,
        supplier_id=2,
        line_items=[
            LineItem(description="Custom Alloy Plate (per spec)", quantity=400, unit_price=70.00),
        ],
        total_amount=28000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 20),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1016,
        supplier_id=2,
        line_items=[
            LineItem(description="Copper Wire Spool (500m)", quantity=30, unit_price=320.00),
        ],
        total_amount=9600.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 1),
        delivery_date=date(2025, 4, 20),
    ),
    # --- CleanSpace Facilities (supplier 3) ---
    PurchaseOrder(
        id=1017,
        supplier_id=3,
        line_items=[
            LineItem(description="Monthly Janitorial Service", quantity=6, unit_price=4500.00),
        ],
        total_amount=27000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 1),
        delivery_date=date(2025, 6, 30),
    ),
    PurchaseOrder(
        id=1018,
        supplier_id=3,
        line_items=[
            LineItem(description="Deep Cleaning Service", quantity=2, unit_price=8000.00),
        ],
        total_amount=16000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 1),
        delivery_date=date(2025, 6, 30),
    ),
    PurchaseOrder(
        id=1019,
        supplier_id=3,
        line_items=[
            LineItem(description="HVAC Maintenance (Annual)", quantity=1, unit_price=18000.00),
        ],
        total_amount=18000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 15),
        delivery_date=date(2025, 4, 15),
    ),
    PurchaseOrder(
        id=1020,
        supplier_id=3,
        line_items=[
            LineItem(description="Emergency Plumbing Repair", quantity=1, unit_price=3500.00),
        ],
        total_amount=3500.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 5),
        delivery_date=date(2025, 2, 10),
    ),
    PurchaseOrder(
        id=1021,
        supplier_id=3,
        line_items=[
            LineItem(description="Carpet Replacement - Floor 2", quantity=1, unit_price=22000.00),
        ],
        total_amount=22000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 20),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1022,
        supplier_id=3,
        line_items=[
            LineItem(description="Window Cleaning (per visit)", quantity=4, unit_price=3000.00),
        ],
        total_amount=12000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 1),
        delivery_date=date(2025, 12, 31),
    ),
    PurchaseOrder(
        id=1023,
        supplier_id=3,
        line_items=[
            LineItem(description="Pest Control Service (quarterly)", quantity=4, unit_price=1200.00),
        ],
        total_amount=4800.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 1),
        delivery_date=date(2025, 5, 15),
    ),
    PurchaseOrder(
        id=1024,
        supplier_id=3,
        line_items=[
            LineItem(description="Parking Lot Maintenance", quantity=10, unit_price=850.00),
        ],
        total_amount=8500.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 25),
        delivery_date=None,
    ),
]

INVOICES: list[Invoice] = [
    # --- Acme Technology Solutions (supplier 1) ---
    Invoice(id=2001, po_id=1001, supplier_id=1, amount=41250.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 5), due_date=date(2025, 3, 7), paid_date=date(2025, 3, 1)),
    Invoice(id=2002, po_id=1003, supplier_id=1, amount=12600.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2024, 12, 5), due_date=date(2025, 1, 4), paid_date=date(2024, 12, 30)),
    Invoice(id=2003, po_id=1004, supplier_id=1, amount=8400.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 20), due_date=date(2025, 4, 19), paid_date=date(2025, 4, 10)),
    Invoice(id=2004, po_id=1005, supplier_id=1, amount=17500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 5), due_date=date(2025, 6, 5), paid_date=None),
    Invoice(id=2005, po_id=1005, supplier_id=1, amount=17500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 5, 1), due_date=date(2025, 7, 1), paid_date=None),
    Invoice(id=2006, po_id=1008, supplier_id=1, amount=9600.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 25), due_date=date(2025, 2, 24), paid_date=date(2025, 2, 15)),
    Invoice(id=2007, po_id=None, supplier_id=1, amount=5200.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 10), due_date=date(2025, 2, 9), paid_date=date(2025, 2, 5)),
    Invoice(id=2008, po_id=None, supplier_id=1, amount=3800.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 2, 10), due_date=date(2025, 3, 12), paid_date=None),
    Invoice(id=2009, po_id=1002, supplier_id=1, amount=13600.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 20), due_date=date(2025, 6, 20), paid_date=None),
    Invoice(id=2010, po_id=None, supplier_id=1, amount=7500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 3, 1), due_date=date(2025, 3, 31), paid_date=None),
    # --- SteelWorks Manufacturing (supplier 2) ---
    Invoice(id=2011, po_id=1009, supplier_id=2, amount=42500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 20), due_date=date(2025, 5, 19), paid_date=date(2025, 5, 10)),
    Invoice(id=2012, po_id=1010, supplier_id=2, amount=12500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 20), due_date=date(2025, 4, 21), paid_date=date(2025, 3, 15)),
    Invoice(id=2013, po_id=1012, supplier_id=2, amount=6400.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 5), due_date=date(2025, 5, 4), paid_date=date(2025, 4, 10)),
    Invoice(id=2014, po_id=1013, supplier_id=2, amount=19500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 1), due_date=date(2025, 6, 30), paid_date=None),
    Invoice(id=2015, po_id=1014, supplier_id=2, amount=21250.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 5, 5), due_date=date(2025, 7, 4), paid_date=None),
    Invoice(id=2016, po_id=1014, supplier_id=2, amount=21250.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 5, 10), due_date=date(2025, 7, 9), paid_date=None),
    Invoice(id=2017, po_id=1016, supplier_id=2, amount=9600.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 4, 25), due_date=date(2025, 6, 24), paid_date=date(2025, 5, 15)),
    Invoice(id=2018, po_id=None, supplier_id=2, amount=12750.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 2, 1), due_date=date(2025, 4, 2), paid_date=None),
    Invoice(id=2019, po_id=None, supplier_id=2, amount=8500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 15), due_date=date(2025, 3, 16), paid_date=date(2025, 3, 10)),
    # --- CleanSpace Facilities (supplier 3) ---
    Invoice(id=2020, po_id=1017, supplier_id=3, amount=4500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 31), due_date=date(2025, 3, 2), paid_date=date(2025, 2, 28)),
    Invoice(id=2021, po_id=1017, supplier_id=3, amount=4500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 28), due_date=date(2025, 3, 30), paid_date=date(2025, 3, 28)),
    Invoice(id=2022, po_id=1017, supplier_id=3, amount=4500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 3, 31), due_date=date(2025, 4, 30), paid_date=None),
    Invoice(id=2023, po_id=1017, supplier_id=3, amount=4500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 30), due_date=date(2025, 6, 30), paid_date=None),
    Invoice(id=2024, po_id=1018, supplier_id=3, amount=8000.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 15), due_date=date(2025, 2, 14), paid_date=date(2025, 2, 10)),
    Invoice(id=2025, po_id=1018, supplier_id=3, amount=8000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 15), due_date=date(2025, 6, 15), paid_date=None),
    Invoice(id=2026, po_id=1019, supplier_id=3, amount=9000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 20), due_date=date(2025, 6, 20), paid_date=None),
    Invoice(id=2027, po_id=1020, supplier_id=3, amount=3500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 12), due_date=date(2025, 3, 14), paid_date=date(2025, 3, 1)),
    Invoice(id=2028, po_id=1022, supplier_id=3, amount=3000.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 15), due_date=date(2025, 4, 14), paid_date=date(2025, 4, 10)),
    Invoice(id=2029, po_id=1023, supplier_id=3, amount=2400.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 5, 20), due_date=date(2025, 7, 19), paid_date=None),
    Invoice(id=2030, po_id=None, supplier_id=3, amount=6500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 2, 28), due_date=date(2025, 3, 30), paid_date=None),
]

CONTRACTS: list[Contract] = [
    Contract(
        id=3001,
        supplier_id=1,
        title="IT Hardware & Services Agreement",
        start_date=date(2024, 1, 1),
        end_date=date(2025, 12, 31),
        annual_value=200000.00,
        currency="USD",
        terms="Volume discount at 15% above $50k annually. Net 30. Covers all hardware, networking, and security equipment.",
        auto_renew=True,
        status=ContractStatus.ACTIVE,
    ),
    Contract(
        id=3002,
        supplier_id=2,
        title="Raw Materials Supply Contract",
        start_date=date(2024, 6, 1),
        end_date=date(2025, 8, 15),
        annual_value=180000.00,
        currency="USD",
        terms="Price locked for contract duration. Delivery within 15 business days. Minimum order $5,000.",
        auto_renew=False,
        status=ContractStatus.PENDING_RENEWAL,
    ),
    Contract(
        id=3003,
        supplier_id=3,
        title="Facilities Management Services",
        start_date=date(2024, 7, 1),
        end_date=date(2025, 6, 30),
        annual_value=54000.00,
        currency="USD",
        terms="Monthly service with 30-day cancellation notice. Covers janitorial, maintenance, and grounds keeping.",
        auto_renew=True,
        status=ContractStatus.ACTIVE,
    ),
]

CATALOG_ITEMS: list[CatalogItem] = [
    # --- Acme Technology Solutions (supplier 1) ---
    CatalogItem(id=4001, supplier_id=1, name="Dell Latitude 5540 Laptop", description="14-inch business laptop, Intel i7, 16GB RAM, 512GB SSD", category="computers", unit_price=1200.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4002, supplier_id=1, name="27-inch 4K Monitor", description="Dell UltraSharp 4K USB-C Hub Monitor", category="monitors", unit_price=450.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4003, supplier_id=1, name="Cisco Meraki MR46 Access Point", description="Cloud-managed WiFi 6 access point", category="networking", unit_price=680.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4004, supplier_id=1, name="Logitech MX Master 3S Mouse", description="Wireless ergonomic mouse, USB-C charging", category="peripherals", unit_price=99.00, currency="USD", lead_time_days=2, in_stock=True),
    CatalogItem(id=4005, supplier_id=1, name="Security Camera - Outdoor", description="4K PoE IP camera with night vision, IP67 rated", category="security", unit_price=350.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4006, supplier_id=1, name="Network Video Recorder (NVR)", description="32-channel NVR with 8TB storage", category="security", unit_price=2800.00, currency="USD", lead_time_days=10, in_stock=False),
    CatalogItem(id=4007, supplier_id=1, name="Managed Network Switch 24-port", description="Cisco Catalyst layer-3 managed switch with PoE+", category="networking", unit_price=1850.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4008, supplier_id=1, name="UPS Battery Backup 1500VA", description="APC Smart-UPS, rack mount, 120V, LCD display", category="power", unit_price=480.00, currency="USD", lead_time_days=3, in_stock=True),
    # --- SteelWorks Manufacturing (supplier 2) ---
    CatalogItem(id=4009, supplier_id=2, name="Steel Sheet 4x8 (Gauge 16)", description="Cold-rolled carbon steel sheet, 1.5mm thickness", category="steel", unit_price=85.00, currency="USD", lead_time_days=10, in_stock=True),
    CatalogItem(id=4010, supplier_id=2, name="Steel Rod 1-inch Diameter", description="A36 hot-rolled steel round bar, 6ft length", category="steel", unit_price=12.50, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4011, supplier_id=2, name="Aluminum Extrusion Profile", description="6063-T5 aluminum, custom T-slot profile, per meter", category="aluminum", unit_price=45.00, currency="USD", lead_time_days=14, in_stock=True),
    CatalogItem(id=4012, supplier_id=2, name="Copper Wire Spool (500m)", description="12 AWG solid copper wire, insulated", category="electrical", unit_price=320.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4013, supplier_id=2, name="Stainless Steel Plate 4x4", description="304 stainless steel, 3mm thickness", category="steel", unit_price=195.00, currency="USD", lead_time_days=12, in_stock=True),
    CatalogItem(id=4014, supplier_id=2, name="Carbon Steel Tube 2-inch", description="Schedule 40 seamless carbon steel, 10ft length", category="steel", unit_price=38.00, currency="USD", lead_time_days=8, in_stock=True),
    CatalogItem(id=4015, supplier_id=2, name="Brass Fitting Assortment", description="50-piece NPT brass fitting kit, 1/4 to 1 inch", category="fittings", unit_price=65.00, currency="USD", lead_time_days=5, in_stock=False),
    # --- CleanSpace Facilities (supplier 3) ---
    CatalogItem(id=4016, supplier_id=3, name="Monthly Janitorial Service", description="Daily cleaning for office up to 20,000 sq ft, includes supplies", category="cleaning", unit_price=4500.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4017, supplier_id=3, name="Deep Cleaning Service", description="Comprehensive deep clean including carpets, windows, and upholstery", category="cleaning", unit_price=8000.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4018, supplier_id=3, name="HVAC Maintenance (Annual)", description="Quarterly inspections, filter replacements, emergency calls included", category="maintenance", unit_price=18000.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4019, supplier_id=3, name="Carpet Cleaning Service", description="Steam cleaning for up to 10,000 sq ft of commercial carpet", category="cleaning", unit_price=2200.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4020, supplier_id=3, name="Window Cleaning (per visit)", description="Interior and exterior window cleaning, up to 5 stories", category="cleaning", unit_price=3000.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4021, supplier_id=3, name="Pest Control (quarterly)", description="Integrated pest management, interior and perimeter treatment", category="maintenance", unit_price=1200.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4022, supplier_id=3, name="Parking Lot Sweeping (monthly)", description="Mechanical sweeping and debris removal for lots up to 2 acres", category="grounds", unit_price=850.00, currency="USD", lead_time_days=2, in_stock=True),
]
