"""Pre-seeded mock procurement data. Resets on server restart."""

from datetime import date

from api.models import (
    CatalogItem,
    Contract,
    ContractStatus,
    Invoice,
    InvoiceStatus,
    LineItem,
    POStatus,
    PurchaseOrder,
    Supplier,
    SupplierCategory,
    SupplierStatus,
)

SUPPLIERS: list[Supplier] = [
    Supplier(
        id=1,
        name="Acme Technology Solutions",
        contact_email="sales@acmetech.com",
        category=SupplierCategory.IT,
        rating=4.5,
        location="San Francisco, CA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2022, 3, 15),
        payment_terms_days=30,
    ),
    Supplier(
        id=2,
        name="Global Office Supplies Inc.",
        contact_email="orders@globaloffice.com",
        category=SupplierCategory.OFFICE_SUPPLIES,
        rating=3.8,
        location="Chicago, IL",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2021, 8, 1),
        payment_terms_days=45,
    ),
    Supplier(
        id=3,
        name="SteelWorks Manufacturing",
        contact_email="procurement@steelworks.com",
        category=SupplierCategory.RAW_MATERIALS,
        rating=4.2,
        location="Pittsburgh, PA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2020, 11, 20),
        payment_terms_days=60,
    ),
    Supplier(
        id=4,
        name="QuickShip Logistics",
        contact_email="dispatch@quickship.com",
        category=SupplierCategory.LOGISTICS,
        rating=4.7,
        location="Memphis, TN",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2023, 1, 10),
        payment_terms_days=15,
    ),
    Supplier(
        id=5,
        name="Pinnacle Consulting Group",
        contact_email="engage@pinnacle.com",
        category=SupplierCategory.PROFESSIONAL_SERVICES,
        rating=4.0,
        location="New York, NY",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2022, 6, 1),
        payment_terms_days=30,
    ),
    Supplier(
        id=6,
        name="CleanSpace Facilities",
        contact_email="service@cleanspace.com",
        category=SupplierCategory.FACILITIES,
        rating=3.5,
        location="Denver, CO",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2023, 4, 15),
        payment_terms_days=30,
    ),
    Supplier(
        id=7,
        name="ByteStream Cloud Services",
        contact_email="enterprise@bytestream.io",
        category=SupplierCategory.IT,
        rating=4.8,
        location="Seattle, WA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2021, 2, 28),
        payment_terms_days=30,
    ),
    Supplier(
        id=8,
        name="Precision Parts Co.",
        contact_email="sales@precisionparts.com",
        category=SupplierCategory.RAW_MATERIALS,
        rating=3.2,
        location="Detroit, MI",
        status=SupplierStatus.INACTIVE,
        onboarded_date=date(2019, 7, 1),
        payment_terms_days=45,
    ),
    Supplier(
        id=9,
        name="Summit Legal Advisors",
        contact_email="info@summitlegal.com",
        category=SupplierCategory.PROFESSIONAL_SERVICES,
        rating=4.6,
        location="Boston, MA",
        status=SupplierStatus.ACTIVE,
        onboarded_date=date(2024, 1, 15),
        payment_terms_days=30,
    ),
    Supplier(
        id=10,
        name="EcoSupply Green Products",
        contact_email="hello@ecosupply.com",
        category=SupplierCategory.OFFICE_SUPPLIES,
        rating=4.1,
        location="Portland, OR",
        status=SupplierStatus.PENDING,
        onboarded_date=date(2024, 11, 1),
        payment_terms_days=30,
    ),
]

PURCHASE_ORDERS: list[PurchaseOrder] = [
    PurchaseOrder(
        id=1001,
        supplier_id=1,
        line_items=[
            LineItem(description="Dell Latitude 5540 Laptop", quantity=25, unit_price=1200.00),
            LineItem(description="27-inch Monitor", quantity=25, unit_price=450.00),
        ],
        total_amount=41250.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 15),
        delivery_date=date(2025, 2, 1),
    ),
    PurchaseOrder(
        id=1002,
        supplier_id=2,
        line_items=[
            LineItem(description="A4 Copy Paper (case)", quantity=200, unit_price=45.00),
            LineItem(description="Ballpoint Pens (box of 50)", quantity=30, unit_price=22.00),
        ],
        total_amount=9660.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 1),
        delivery_date=date(2025, 2, 10),
    ),
    PurchaseOrder(
        id=1003,
        supplier_id=3,
        line_items=[
            LineItem(description="Steel Sheet 4x8 (gauge 16)", quantity=500, unit_price=85.00),
            LineItem(description="Steel Rod 1-inch diameter", quantity=1000, unit_price=12.50),
        ],
        total_amount=55000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 10),
        delivery_date=date(2025, 4, 15),
    ),
    PurchaseOrder(
        id=1004,
        supplier_id=4,
        line_items=[
            LineItem(description="Freight shipping - West Coast route", quantity=12, unit_price=3500.00),
        ],
        total_amount=42000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 3, 20),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1005,
        supplier_id=5,
        line_items=[
            LineItem(description="Strategy consulting - Q2 engagement", quantity=1, unit_price=75000.00),
        ],
        total_amount=75000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 15),
        delivery_date=date(2025, 6, 30),
    ),
    PurchaseOrder(
        id=1006,
        supplier_id=7,
        line_items=[
            LineItem(description="Cloud hosting - annual license", quantity=1, unit_price=120000.00),
            LineItem(description="Premium support tier", quantity=1, unit_price=24000.00),
        ],
        total_amount=144000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 5),
        delivery_date=date(2025, 1, 10),
    ),
    PurchaseOrder(
        id=1007,
        supplier_id=1,
        line_items=[
            LineItem(description="Cisco Meraki Access Points", quantity=40, unit_price=680.00),
        ],
        total_amount=27200.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 1),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1008,
        supplier_id=6,
        line_items=[
            LineItem(description="Monthly janitorial service", quantity=6, unit_price=4500.00),
            LineItem(description="Deep cleaning - quarterly", quantity=2, unit_price=8000.00),
        ],
        total_amount=43000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 1),
        delivery_date=date(2025, 6, 30),
    ),
    PurchaseOrder(
        id=1009,
        supplier_id=3,
        line_items=[
            LineItem(description="Aluminum Extrusion Profile", quantity=200, unit_price=45.00),
        ],
        total_amount=9000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 10),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1010,
        supplier_id=2,
        line_items=[
            LineItem(description="Ergonomic Office Chairs", quantity=50, unit_price=399.00),
            LineItem(description="Standing Desk Converters", quantity=25, unit_price=275.00),
        ],
        total_amount=26825.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2024, 12, 1),
        delivery_date=date(2024, 12, 20),
    ),
    PurchaseOrder(
        id=1011,
        supplier_id=9,
        line_items=[
            LineItem(description="IP Patent Filing Services", quantity=3, unit_price=15000.00),
        ],
        total_amount=45000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 1),
        delivery_date=date(2025, 5, 31),
    ),
    PurchaseOrder(
        id=1012,
        supplier_id=4,
        line_items=[
            LineItem(description="Express courier - international", quantity=50, unit_price=125.00),
        ],
        total_amount=6250.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 2, 20),
        delivery_date=date(2025, 3, 5),
    ),
    PurchaseOrder(
        id=1013,
        supplier_id=7,
        line_items=[
            LineItem(description="Data analytics platform - seats", quantity=100, unit_price=50.00),
        ],
        total_amount=5000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 15),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1014,
        supplier_id=5,
        line_items=[
            LineItem(description="Executive coaching sessions", quantity=10, unit_price=2500.00),
        ],
        total_amount=25000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 5),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1015,
        supplier_id=1,
        line_items=[
            LineItem(description="Security cameras - outdoor", quantity=20, unit_price=350.00),
            LineItem(description="NVR system", quantity=2, unit_price=2800.00),
        ],
        total_amount=12600.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2024, 11, 15),
        delivery_date=date(2024, 12, 1),
    ),
    PurchaseOrder(
        id=1016,
        supplier_id=6,
        line_items=[
            LineItem(description="HVAC maintenance contract", quantity=1, unit_price=18000.00),
        ],
        total_amount=18000.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 3, 15),
        delivery_date=date(2025, 12, 31),
    ),
    PurchaseOrder(
        id=1017,
        supplier_id=8,
        line_items=[
            LineItem(description="Custom machined brackets", quantity=500, unit_price=8.50),
        ],
        total_amount=4250.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 2, 1),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1018,
        supplier_id=10,
        line_items=[
            LineItem(description="Recycled notebooks (case)", quantity=100, unit_price=35.00),
            LineItem(description="Bamboo pen set", quantity=200, unit_price=12.00),
        ],
        total_amount=5900.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 20),
        delivery_date=None,
    ),
    PurchaseOrder(
        id=1019,
        supplier_id=3,
        line_items=[
            LineItem(description="Copper Wire Spool (500m)", quantity=20, unit_price=320.00),
        ],
        total_amount=6400.00,
        currency="USD",
        status=POStatus.ACKNOWLEDGED,
        created_date=date(2025, 1, 25),
        delivery_date=date(2025, 2, 15),
    ),
    PurchaseOrder(
        id=1020,
        supplier_id=9,
        line_items=[
            LineItem(description="Contract review - vendor agreements", quantity=8, unit_price=5000.00),
        ],
        total_amount=40000.00,
        currency="USD",
        status=POStatus.SUBMITTED,
        created_date=date(2025, 4, 8),
        delivery_date=None,
    ),
]

INVOICES: list[Invoice] = [
    Invoice(id=2001, po_id=1001, supplier_id=1, amount=41250.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 5), due_date=date(2025, 3, 7), paid_date=date(2025, 3, 1)),
    Invoice(id=2002, po_id=1002, supplier_id=2, amount=9660.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 12), due_date=date(2025, 3, 29), paid_date=date(2025, 3, 25)),
    Invoice(id=2003, po_id=1006, supplier_id=7, amount=72000.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 10), due_date=date(2025, 2, 9), paid_date=date(2025, 2, 5)),
    Invoice(id=2004, po_id=1006, supplier_id=7, amount=72000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 1), due_date=date(2025, 5, 1), paid_date=None),
    Invoice(id=2005, po_id=1005, supplier_id=5, amount=37500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 3, 31), due_date=date(2025, 4, 30), paid_date=None),
    Invoice(id=2006, po_id=1008, supplier_id=6, amount=4500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 31), due_date=date(2025, 3, 2), paid_date=date(2025, 2, 28)),
    Invoice(id=2007, po_id=1008, supplier_id=6, amount=4500.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 28), due_date=date(2025, 3, 30), paid_date=date(2025, 3, 28)),
    Invoice(id=2008, po_id=1008, supplier_id=6, amount=4500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 3, 31), due_date=date(2025, 4, 30), paid_date=None),
    Invoice(id=2009, po_id=1010, supplier_id=2, amount=26825.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2024, 12, 22), due_date=date(2025, 2, 5), paid_date=date(2025, 1, 30)),
    Invoice(id=2010, po_id=1012, supplier_id=4, amount=6250.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 6), due_date=date(2025, 3, 21), paid_date=date(2025, 3, 18)),
    Invoice(id=2011, po_id=1015, supplier_id=1, amount=12600.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2024, 12, 5), due_date=date(2025, 1, 4), paid_date=date(2024, 12, 30)),
    Invoice(id=2012, po_id=1003, supplier_id=3, amount=27500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 1), due_date=date(2025, 5, 31), paid_date=None),
    Invoice(id=2013, po_id=1019, supplier_id=3, amount=6400.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 2, 16), due_date=date(2025, 4, 17), paid_date=date(2025, 4, 10)),
    Invoice(id=2014, po_id=1004, supplier_id=4, amount=14000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 5), due_date=date(2025, 4, 20), paid_date=None),
    Invoice(id=2015, po_id=1005, supplier_id=5, amount=37500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 2, 15), due_date=date(2025, 3, 17), paid_date=None),
    Invoice(id=2016, po_id=1011, supplier_id=9, amount=15000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 3, 15), due_date=date(2025, 4, 14), paid_date=None),
    Invoice(id=2017, po_id=1008, supplier_id=6, amount=8000.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 1, 15), due_date=date(2025, 2, 14), paid_date=None),
    Invoice(id=2018, po_id=1007, supplier_id=1, amount=13600.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 10), due_date=date(2025, 5, 10), paid_date=None),
    Invoice(id=2019, po_id=1016, supplier_id=6, amount=9000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 1), due_date=date(2025, 5, 1), paid_date=None),
    Invoice(id=2020, po_id=None, supplier_id=3, amount=12750.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 2, 1), due_date=date(2025, 4, 2), paid_date=None),
    Invoice(id=2021, po_id=1011, supplier_id=9, amount=15000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 15), due_date=date(2025, 5, 15), paid_date=None),
    Invoice(id=2022, po_id=1003, supplier_id=3, amount=27500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 20), due_date=date(2025, 6, 19), paid_date=None),
    Invoice(id=2023, po_id=None, supplier_id=7, amount=5000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 18), due_date=date(2025, 5, 18), paid_date=None),
    Invoice(id=2024, po_id=1004, supplier_id=4, amount=14000.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 20), due_date=date(2025, 5, 5), paid_date=None),
    Invoice(id=2025, po_id=None, supplier_id=5, amount=12500.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 1, 20), due_date=date(2025, 2, 19), paid_date=None),
    Invoice(id=2026, po_id=1010, supplier_id=2, amount=6875.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 1, 5), due_date=date(2025, 2, 19), paid_date=date(2025, 2, 15)),
    Invoice(id=2027, po_id=None, supplier_id=1, amount=8500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 22), due_date=date(2025, 5, 22), paid_date=None),
    Invoice(id=2028, po_id=1014, supplier_id=5, amount=12500.00, currency="USD", status=InvoiceStatus.PENDING, issued_date=date(2025, 4, 25), due_date=date(2025, 5, 25), paid_date=None),
    Invoice(id=2029, po_id=None, supplier_id=4, amount=3200.00, currency="USD", status=InvoiceStatus.PAID, issued_date=date(2025, 3, 10), due_date=date(2025, 3, 25), paid_date=date(2025, 3, 22)),
    Invoice(id=2030, po_id=None, supplier_id=2, amount=1850.00, currency="USD", status=InvoiceStatus.OVERDUE, issued_date=date(2025, 3, 1), due_date=date(2025, 4, 15), paid_date=None),
]

CONTRACTS: list[Contract] = [
    Contract(id=3001, supplier_id=7, title="Cloud Infrastructure Services Agreement", start_date=date(2025, 1, 1), end_date=date(2025, 12, 31), annual_value=144000.00, currency="USD", terms="Annual commitment with quarterly billing. 99.9% uptime SLA.", auto_renew=True, status=ContractStatus.ACTIVE),
    Contract(id=3002, supplier_id=5, title="Strategic Consulting Engagement", start_date=date(2025, 1, 1), end_date=date(2025, 6, 30), annual_value=150000.00, currency="USD", terms="Fixed fee per engagement. Monthly progress reviews required.", auto_renew=False, status=ContractStatus.ACTIVE),
    Contract(id=3003, supplier_id=6, title="Facilities Management Services", start_date=date(2024, 7, 1), end_date=date(2025, 6, 30), annual_value=54000.00, currency="USD", terms="Monthly service with 30-day cancellation notice.", auto_renew=True, status=ContractStatus.ACTIVE),
    Contract(id=3004, supplier_id=1, title="IT Hardware Supply Agreement", start_date=date(2024, 1, 1), end_date=date(2025, 12, 31), annual_value=200000.00, currency="USD", terms="Volume discount at 15% above $50k annually. Net 30.", auto_renew=True, status=ContractStatus.ACTIVE),
    Contract(id=3005, supplier_id=3, title="Raw Materials Supply Contract", start_date=date(2024, 6, 1), end_date=date(2025, 5, 31), annual_value=180000.00, currency="USD", terms="Price locked for contract duration. Delivery within 15 business days.", auto_renew=False, status=ContractStatus.PENDING_RENEWAL),
    Contract(id=3006, supplier_id=4, title="Logistics and Freight Services", start_date=date(2025, 1, 1), end_date=date(2026, 12, 31), annual_value=96000.00, currency="USD", terms="Preferred rates for volumes exceeding 10 shipments/month.", auto_renew=True, status=ContractStatus.ACTIVE),
    Contract(id=3007, supplier_id=9, title="Legal Advisory Retainer", start_date=date(2025, 1, 1), end_date=date(2025, 12, 31), annual_value=90000.00, currency="USD", terms="Monthly retainer with overflow billed at $500/hr.", auto_renew=True, status=ContractStatus.ACTIVE),
    Contract(id=3008, supplier_id=8, title="Precision Machining Supply", start_date=date(2023, 1, 1), end_date=date(2024, 12, 31), annual_value=60000.00, currency="USD", terms="Custom orders with 20-day lead time.", auto_renew=False, status=ContractStatus.EXPIRED),
]

CATALOG_ITEMS: list[CatalogItem] = [
    # IT - Acme Technology (supplier 1)
    CatalogItem(id=4001, supplier_id=1, name="Dell Latitude 5540 Laptop", description="14-inch business laptop, Intel i7, 16GB RAM, 512GB SSD", category="computers", unit_price=1200.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4002, supplier_id=1, name="27-inch 4K Monitor", description="Dell UltraSharp 4K USB-C Hub Monitor", category="monitors", unit_price=450.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4003, supplier_id=1, name="Cisco Meraki MR46 Access Point", description="Cloud-managed WiFi 6 access point", category="networking", unit_price=680.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4004, supplier_id=1, name="Logitech MX Master 3S Mouse", description="Wireless ergonomic mouse, USB-C charging", category="peripherals", unit_price=99.00, currency="USD", lead_time_days=2, in_stock=True),
    CatalogItem(id=4005, supplier_id=1, name="Security Camera - Outdoor", description="4K PoE IP camera with night vision, IP67 rated", category="security", unit_price=350.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4006, supplier_id=1, name="Network Video Recorder (NVR)", description="32-channel NVR with 8TB storage", category="security", unit_price=2800.00, currency="USD", lead_time_days=10, in_stock=False),
    # Office Supplies - Global Office (supplier 2)
    CatalogItem(id=4007, supplier_id=2, name="A4 Copy Paper (Case of 10 reams)", description="80gsm white multi-purpose paper, 5000 sheets", category="paper", unit_price=45.00, currency="USD", lead_time_days=2, in_stock=True),
    CatalogItem(id=4008, supplier_id=2, name="Ballpoint Pens (Box of 50)", description="Medium point blue ink, retractable", category="writing", unit_price=22.00, currency="USD", lead_time_days=2, in_stock=True),
    CatalogItem(id=4009, supplier_id=2, name="Ergonomic Office Chair", description="Mesh back, adjustable lumbar, armrests, and height", category="furniture", unit_price=399.00, currency="USD", lead_time_days=10, in_stock=True),
    CatalogItem(id=4010, supplier_id=2, name="Standing Desk Converter", description="Height-adjustable sit-stand desktop riser, 36-inch", category="furniture", unit_price=275.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4011, supplier_id=2, name="Whiteboard 6x4 ft", description="Magnetic dry-erase whiteboard with aluminum frame", category="office_equipment", unit_price=189.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4012, supplier_id=2, name="File Cabinet (4-drawer)", description="Lateral filing cabinet, lockable, legal/letter size", category="furniture", unit_price=320.00, currency="USD", lead_time_days=12, in_stock=False),
    # Raw Materials - SteelWorks (supplier 3)
    CatalogItem(id=4013, supplier_id=3, name="Steel Sheet 4x8 (Gauge 16)", description="Cold-rolled carbon steel sheet, 1.5mm thickness", category="steel", unit_price=85.00, currency="USD", lead_time_days=10, in_stock=True),
    CatalogItem(id=4014, supplier_id=3, name="Steel Rod 1-inch Diameter", description="A36 hot-rolled steel round bar, 6ft length", category="steel", unit_price=12.50, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4015, supplier_id=3, name="Aluminum Extrusion Profile", description="6063-T5 aluminum, custom T-slot profile, per meter", category="aluminum", unit_price=45.00, currency="USD", lead_time_days=14, in_stock=True),
    CatalogItem(id=4016, supplier_id=3, name="Copper Wire Spool (500m)", description="12 AWG solid copper wire, insulated", category="electrical", unit_price=320.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4017, supplier_id=3, name="Stainless Steel Plate 4x4", description="304 stainless steel, 3mm thickness", category="steel", unit_price=195.00, currency="USD", lead_time_days=12, in_stock=False),
    # Logistics - QuickShip (supplier 4)
    CatalogItem(id=4018, supplier_id=4, name="Standard Freight - Domestic", description="Full truckload, continental US, 3-5 business days", category="shipping", unit_price=2800.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4019, supplier_id=4, name="Express Freight - Domestic", description="Full truckload, continental US, next business day", category="shipping", unit_price=4500.00, currency="USD", lead_time_days=1, in_stock=True),
    CatalogItem(id=4020, supplier_id=4, name="International Express Courier", description="Door-to-door international, 2-3 business days, up to 30kg", category="courier", unit_price=125.00, currency="USD", lead_time_days=3, in_stock=True),
    CatalogItem(id=4021, supplier_id=4, name="Warehousing - Per Pallet/Month", description="Climate-controlled warehouse storage, Memphis hub", category="storage", unit_price=45.00, currency="USD", lead_time_days=1, in_stock=True),
    # Professional Services - Pinnacle (supplier 5)
    CatalogItem(id=4022, supplier_id=5, name="Strategy Consulting (per day)", description="Senior consultant, on-site or remote", category="consulting", unit_price=3500.00, currency="USD", lead_time_days=14, in_stock=True),
    CatalogItem(id=4023, supplier_id=5, name="Executive Coaching Session", description="1:1 coaching, 90-minute session with certified coach", category="coaching", unit_price=2500.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4024, supplier_id=5, name="Workshop Facilitation (full day)", description="Team workshop, up to 20 participants, includes materials", category="training", unit_price=8000.00, currency="USD", lead_time_days=21, in_stock=True),
    # Facilities - CleanSpace (supplier 6)
    CatalogItem(id=4025, supplier_id=6, name="Monthly Janitorial Service", description="Daily cleaning for office up to 20,000 sq ft", category="cleaning", unit_price=4500.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4026, supplier_id=6, name="Deep Cleaning Service", description="Comprehensive deep clean including carpets and windows", category="cleaning", unit_price=8000.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4027, supplier_id=6, name="HVAC Maintenance (Annual)", description="Quarterly inspections, filter replacements, emergency calls", category="maintenance", unit_price=18000.00, currency="USD", lead_time_days=3, in_stock=True),
    # IT - ByteStream (supplier 7)
    CatalogItem(id=4028, supplier_id=7, name="Cloud Hosting - Standard", description="8 vCPU, 32GB RAM, 500GB SSD, per month", category="cloud", unit_price=450.00, currency="USD", lead_time_days=1, in_stock=True),
    CatalogItem(id=4029, supplier_id=7, name="Cloud Hosting - Enterprise", description="32 vCPU, 128GB RAM, 2TB SSD, per month", category="cloud", unit_price=1800.00, currency="USD", lead_time_days=1, in_stock=True),
    CatalogItem(id=4030, supplier_id=7, name="Data Analytics Platform (per seat/month)", description="Full BI suite with dashboards, reports, and data pipelines", category="software", unit_price=50.00, currency="USD", lead_time_days=1, in_stock=True),
    CatalogItem(id=4031, supplier_id=7, name="Premium Support Tier (annual)", description="24/7 support, 15-min response SLA, dedicated TAM", category="support", unit_price=24000.00, currency="USD", lead_time_days=1, in_stock=True),
    # Raw Materials - Precision Parts (supplier 8)
    CatalogItem(id=4032, supplier_id=8, name="Custom Machined Bracket", description="CNC aluminum bracket, per engineering spec", category="machined_parts", unit_price=8.50, currency="USD", lead_time_days=20, in_stock=False),
    CatalogItem(id=4033, supplier_id=8, name="Precision Gear Set", description="Hardened steel gear pair, custom ratio", category="machined_parts", unit_price=145.00, currency="USD", lead_time_days=25, in_stock=False),
    # Legal - Summit (supplier 9)
    CatalogItem(id=4034, supplier_id=9, name="Contract Review", description="Review and redline of vendor/supplier agreement", category="legal", unit_price=5000.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4035, supplier_id=9, name="IP Patent Filing", description="Full patent application preparation and filing", category="legal", unit_price=15000.00, currency="USD", lead_time_days=30, in_stock=True),
    CatalogItem(id=4036, supplier_id=9, name="Compliance Audit", description="Regulatory compliance review and gap analysis", category="legal", unit_price=25000.00, currency="USD", lead_time_days=21, in_stock=True),
    # Eco - EcoSupply (supplier 10)
    CatalogItem(id=4037, supplier_id=10, name="Recycled Notebooks (Case of 50)", description="A5 notebooks, 80% post-consumer recycled paper", category="paper", unit_price=35.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4038, supplier_id=10, name="Bamboo Pen Set (10-pack)", description="Refillable ballpoint pens with bamboo barrel", category="writing", unit_price=12.00, currency="USD", lead_time_days=5, in_stock=True),
    CatalogItem(id=4039, supplier_id=10, name="Compostable Coffee Cups (500)", description="12oz hot cups, PLA-lined, commercially compostable", category="kitchen", unit_price=65.00, currency="USD", lead_time_days=7, in_stock=True),
    CatalogItem(id=4040, supplier_id=10, name="Recycled Toner Cartridge - HP", description="Remanufactured, compatible with HP LaserJet Pro series", category="printing", unit_price=42.00, currency="USD", lead_time_days=3, in_stock=True),
]
